name: app_theme
description: Flutter theme with spacings
version: 0.0.1
homepage: https://github.com/cedvdb/flutter_app_theme

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

